# BUILD

.docker-runner:
  stage: build
  tags:
    - docker
  image: $CI_REGISTRY/$CI_PROJECT_PATH/docker:24.0.4-git
  services:
    - name: $CI_REGISTRY/$CI_PROJECT_PATH/docker:24.0.4-dind
      alias: docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

.pull:
  extends: .docker-runner
  script:
    - |
        if [[ $(docker image ls --quiet $CI_REGISTRY/$CI_PROJECT_PATH/$IMAGE:$TAG) ]]; then
          echo "image already pulled"
        else
          docker pull $IMAGE:$TAG
          docker tag $IMAGE:$TAG $CI_REGISTRY/$CI_PROJECT_PATH/$IMAGE:$TAG
          docker push $CI_REGISTRY/$CI_PROJECT_PATH/$IMAGE:$TAG
        fi

pull-node:
  extends: .pull
  variables:
    IMAGE: node
    TAG: 20.11.1-buster


# TEST

.frontend:
  stage: test
  needs:
    - "pull-node"
  image: $CI_REGISTRY/$CI_PROJECT_PATH/node:20.11.1-buster
  variables:
    ELM_HOME: "$CI_PROJECT_DIR/.elm"
    NPM_CACHE: "$CI_PROJECT_DIR/.npm"
  cache:
    untracked: true
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .elm/
      - .npm/
      - node_modules/
  before_script:
    - npm config set cache $NPM_CACHE
    - npm config set prefer-offline true
    - npm install

format:
  extends: .frontend
  script: npm run format

test:
  extends: .frontend
  script: npm run test

review:
  extends: .frontend
  script: npm run review

licenses-nodejs:
  extends: .frontend
  script:
    - npm run licenses:nodejs
    - git --no-pager diff
    - git update-index --refresh
    - git diff-index --quiet HEAD --
